"""verifycode

Revision ID: 30c0ba0e63e1
Revises: 6f2ac2319e21
Create Date: 2019-01-26 21:47:44.106413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c0ba0e63e1'
down_revision = '6f2ac2319e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regist_code', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('regist_code', sa.Column('verify_code', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_regist_code_email'), 'regist_code', ['email'], unique=True)
    op.create_index(op.f('ix_regist_code_verify_code'), 'regist_code', ['verify_code'], unique=False)
    op.drop_index('ix_regist_code_random_code', table_name='regist_code')
    op.drop_column('regist_code', 'random_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regist_code', sa.Column('random_code', sa.INTEGER(), nullable=True))
    op.create_index('ix_regist_code_random_code', 'regist_code', ['random_code'], unique=False)
    op.drop_index(op.f('ix_regist_code_verify_code'), table_name='regist_code')
    op.drop_index(op.f('ix_regist_code_email'), table_name='regist_code')
    op.drop_column('regist_code', 'verify_code')
    op.drop_column('regist_code', 'email')
    # ### end Alembic commands ###
