"""add user.email and others

Revision ID: 56b4d215f1bc
Revises: be9e3bf0fbe2
Create Date: 2019-01-22 15:09:01.115743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b4d215f1bc'
down_revision = 'be9e3bf0fbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_time'), 'post', ['time'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_post_time'), table_name='post')
    # ### end Alembic commands ###
