"""User and RegistCode

Revision ID: 6f2ac2319e21
Revises: 56b4d215f1bc
Create Date: 2019-01-26 12:10:30.452562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2ac2319e21'
down_revision = '56b4d215f1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regist_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('random_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regist_code_random_code'), 'regist_code', ['random_code'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_index(op.f('ix_regist_code_random_code'), table_name='regist_code')
    op.drop_table('regist_code')
    # ### end Alembic commands ###
