"""empty message

Revision ID: 8e622386e11b
Revises: 4fe6ec54e179
Create Date: 2019-02-23 17:37:27.807853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e622386e11b'
down_revision = '4fe6ec54e179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_message', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=140),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=210),
               existing_nullable=True)
    op.alter_column('leave_message', 'email',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=48),
               existing_nullable=True)
    op.alter_column('post', 'content',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.String(length=20000),
               existing_nullable=True)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('regist_code', 'verify_code',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('upload_image', 'image_path',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_image', 'image_path',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('regist_code', 'verify_code',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('post', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.String(length=20000),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=True)
    op.alter_column('leave_message', 'email',
               existing_type=sa.String(length=48),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('leave_message', 'content',
               existing_type=sa.String(length=210),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
