"""add loginrecord and new code_method

Revision ID: dd91bf6531e6
Revises: e8c2411d911c
Create Date: 2019-02-02 16:14:31.669161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd91bf6531e6'
down_revision = 'e8c2411d911c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('login_ip', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_record_login_time'), 'login_record', ['login_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_record_login_time'), table_name='login_record')
    op.drop_table('login_record')
    # ### end Alembic commands ###
